{
 "title": "KPOps default Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Pipeline", "query": { "query": "kube_pod_labels" } },
   { "name": "ErrorSuffix", "query": "error-topic" }
  ]
 },
 "panels": [
  {
   "title": "$Pipeline pipeline - messages in per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic=~\".*$Pipeline-.*-topic\"}[5m])) unless sum by(topic) (rate(kafka_topic_partition_current_offset{topic=~\".*$Pipeline-.*-dead-letter-topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$Pipeline pipeline - lag of consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(group) (rate(kafka_consumergroup_group_topic_sum_lag{group=~\".*$Pipeline.*\"}[5m]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$Pipeline pipeline - dead letters per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partition_current_offset{topic=~\".*$Pipeline.*$ErrorSuffix\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}