on:
  issues:
    types:
      - opened

jobs:
  create-update-project:
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
        with:
          project-url: https://github.com/users/MichaelKora/projects/4
          github-token: ${{ secrets.MY_TOKEN }}
        id: add-project
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751
        with:
          project-url: https://github.com/users/MichaelKora/projects/4
          github-token: ${{ secrets.MY_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Status
          field-values: Backlog