on:
  issues:
    types:
      - opened

jobs:
  create-update-project:
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
        with:
          project-url: https://github.com/users/MichaelKora/projects/4
          github-token: ${{ secrets.MY_TOKEN }}
        id: add-project
