name: Reusable workflow for packaging and publishing Helm charts on GitHub pages

on:
  workflow_call:
    inputs:
      start-run:
        description: "Describes if thats the first time the workflow will be run. because if that is the first time then there are multiple subdir with one index.yaml each"
        required: true
        type: string
jobs:
  first-job:
#    if: ${{ inputs.start-run == 'true' }}
    needs: helm-lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stage: [producer-app, producer-app-cleanup-job, rclone-copy, streams-app, streams-app-cleanup-job]
    env:
      charts-subdir: "${{ matrix.stage }}"

    steps:
      - name: echo1
        run: echo "Hello world"
        shell: bash

      - name: echo 2
        run: echo "Hello world"
        shell: bash