name: matrix test


on:
  workflow_dispatch:
    inputs:
      start-run:
        description: "Describes if thats the first time the workflow will be run. because if that is the first time then there are multiple subdir with one index.yaml each"
        required: true
        type: string
jobs:
  first-job:
    runs-on: ubuntu-22.04
    if: ${{ inputs.start-run == 'true' }}
    strategy:
      matrix:
        stage: [producer-app, producer-app-cleanup-job, rclone-copy, streams-app, streams-app-cleanup-job]
    env:
      charts-subdir: "${{ matrix.stage }}"

    steps:
      - name: echo1
        run: echo ${{ env.charts-subdir }}
        shell: bash
  second-job:
    if: ${{ inputs.start-run == 'false' }}
    runs-on: ubuntu-22.04
    env:
      charts-subdir: "root-dir"

    steps:
      - name: echo1
        run: echo ${{ env.charts-subdir }}
        shell: bash
